version: '3.8'

services:
  backend:
    build: ./Email-Platform-Backend
    ports:
      - "8000:8000"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://admin:postgres@db:5432/email_platform
    depends_on:
      - db

  frontend:
    build: ./Email-Platform-Frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=email_platform
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: