"""Update user and template models

Revision ID: 6b4b7c8e4842
Revises: ac5e431df75b
Create Date: 2024-09-30 00:17:00.804270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b4b7c8e4842'
down_revision: Union[str, None] = 'ac5e431df75b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attachments_filename', table_name='attachments')
    op.drop_index('ix_attachments_id', table_name='attachments')
    op.drop_table('attachments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('email_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], name='attachments_email_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='attachments_pkey')
    )
    op.create_index('ix_attachments_id', 'attachments', ['id'], unique=False)
    op.create_index('ix_attachments_filename', 'attachments', ['filename'], unique=False)
    # ### end Alembic commands ###
